# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170405_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Quotes',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='PageCount',
        ),
        migrations.RenameField(
            model_name='quotes',
            old_name='question_text',
            new_name='quote_text',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
