# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170424_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='quote_text',
            new_name='quotes_text',
        ),
    ]
