# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 00:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170428_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
