# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 00:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170429_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
